### PR TITLE
use external messaging to avoid reload after installation

### PR DESCRIPTION
**Pull request by fippo**
Still needs more testing. @legastero @xdumaine 

The "old" way is still supported. The trigger for using the "new" way is a sessionStorage flag. Slightly ugly, but...

### CODE REVIEW

**Comment by xdumaine** [comment]
Unless I'm missing something, it looks like this requires changes to background.js in the extension that I don't see in this PR. I had it changed to 

```javascript
    chrome.runtime.onMessageExternal.addListener(function (message, sender, callback) {
        switch(message.type) {
        case 'getScreen':
            var pending = chrome.desktopCapture.chooseDesktopMedia(message.options || ['screen', 'window'],
                                                                   sender.tab, function (streamid) {
                // communicate this string to the app so it can call getUserMedia with it
                message.type = 'gotScreen';
                message.sourceId = streamid;
                callback(message);
            });
            // let the app know that it can cancel the timeout
            message.type = 'getScreenPending';
            message.request = pending;
            callback(message);
            break;
        case 'cancelGetScreen':
            chrome.desktopCapture.cancelChooseDesktopMedia(message.request);
            message.type = 'canceledGetScreen';
            callback(message);
            break;
        }
    });
```

**Comment by fippo** [comment]
@xdumaine can you merge that please?
You probably still lack the perm to publish this and simplewebrtc on npm, but @legastero probably fix that next week

:-)

**Comment by xdumaine** [comment]
Just wanted to clarify - you want me to merge this PR? It looks good to me.

**Comment by fippo** [comment]
yes!

**Comment by fippo** [comment]
minor version bump to 1.4.0 with updated bundle.

**Comment by xdumaine** [comment]
@fippo on the talky side, how did you determine that the extension was installed? Looks like the success handler is called before the background script is ready. Timeout?

**Comment by fippo** [comment]
works roughly as follows -- i.e. uses the webstore success callback to restart.
```
                return chrome.webstore.install(
                    EXTENSION_URL,
                    function () {
                        sessionStorage.getScreenMediaJSExtensionId = EXTENSION_ID;
                        mediaController.startScreenShare(done);
                    },
                    done
                );
```

**Pull request merged**
